### ISSUE TITLE
BandageNG unable to visualize `consensus_assembly.gfa`

### ISSUE THREAD

**Issue by ericvdtoorn** [rrwick/Autocycler#17]
Running BangageNG, it does open the file but does not seem to process the base lengths, resulting in 0bp being assigned: 

![Image](https://github.com/user-attachments/assets/14841c1e-12b4-428e-9fab-f22228c564bd)

Actual stats:
```yaml
consensus_assembly_bases: 3077319
consensus_assembly_unitigs: 3
consensus_assembly_fully_resolved: true
consensus_assembly_clusters:
- length: 2945475
  unitigs: 1
  topology: circular
- length: 85637
  unitigs: 1
  topology: circular
- length: 46207
  unitigs: 1
  topology: circular
```

Is this an issue with BandageNG or is the assembly that's output not confo
Actual GFA:
[consensus_assembly.gfa.zip](https://github.com/user-attachments/files/19491411/consensus_assembly.gfa.zip)

rm the gfa format? `any2fasta` does work, so does seem to 

Error output:
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
error: while parsing grammar::tag
     |
   1 | S\t1\tAAAAAACACGTCAATTTCTTGACGTGTTTAA...z:steelblue
     |                                         ^ invalid tag type

error: while parsing grammar::tag
     |
   1 | S\t2\tGTCCGTTCAGAATTATTCATGATGCAACTTG...z:steelblue
     |                                         ^ invalid tag type

error: while parsing grammar::tag
     |
   1 | S\t3\tCCGGAACGACTAATGACGAGGGGCAACTAAC...z:steelblue
     |                                         ^ invalid tag type
```
