### ISSUE TITLE
Subset overlap stats for autocycler subsample

### ISSUE THREAD

**Issue by blaiseli** [rrwick/Autocycler#4]
I'm looking at the output of `autocycler subsample` and realize that, with some of my data, there is probably little independance between my read subsets.

Here is the content of `subsample.yaml`:

```
input_read_count: 11156
input_read_bases: 51574751
input_read_n50: 6472
output_reads:
- count: 11121
  bases: 51420714
  n50: 6478
- count: 11121
  bases: 51393181
  n50: 6471
- count: 11121
  bases: 51420713
  n50: 6474
- count: 11121
  bases: 51422897
  n50: 6477
```

If I understand correctly, each of the four subsample consists of 11121 out of the 11156 input reads, with only 35 reads (11156 - 11121) not included in each.

Is that correct?

I would like to compute how many reads each pair of subsets have in common (or have at least the minimum and maximum of these numbers), and what proportion this corresponds to.

Is that something easy to compute?
I so, it might be a useful statistic to include in the output of `autocycler subsample`, possibly with a warning when read subsets have too many reads in common.
